export enum BlogType {
  SUSTAINABLE_LIVING = 'SUSTAINABLE_LIVING',
  CONSCIOUS_CONSUMPTION = 'CONSCIOUS_CONSUMPTION',
  ENVIRONMENT_AND_PLANET = 'ENVIRONMENT_AND_PLANET',
  GREEN_ENTREPRENEURSHIP = 'GREEN_ENTREPRENEURSHIP',
  COMMUNITY_AND_PLATFORM = 'COMMUNITY_AND_PLATFORM',
  EKORU_TIPS = 'EKORU_TIPS',
}

export enum Language {
  ES = 'ES',
  EN = 'EN',
  FR = 'FR',
  PT = 'PT',
  DE = 'DE',
}

export enum BlogReactionType {
  LIKE = 'LIKE',
  DISLIKE = 'DISLIKE',
}
